[versions]
minecraft = "1.21.1"
ragium = "0.3.0"

parchment-mc = "1.21.1"
parchment-map = "2024.11.17"

neo-moddev = "2.0.78"
neo-version = "21.1.127"

kff-version = "5.7.0"
kff-version-range = "[5.7,)"
ktlint = "12.1.2"

aa = "1.3.15+mc1.21.1"
create = "1.21.1-6.0.0"
delight = "1.21.1-1.2.7"
eio = "7.1.6-alpha"
if = "1.21-3.6.23"
immersive = "1.21.1-12.0.0-182.88"
jade = "15.9.4+neoforge"
jei = "19.21.0.247"
mek = "1.21.1-10.7.8.70"
mi = "2.2.34"
patchouli-gen = "1.21.1-1.0.11-Snapshot.3"
rc = "1.2.5"
tf = "4.6.3003"

[libraries]

kff = { group = "thedarkcolour", name = "kotlinforforge-neoforge", version.ref = "kff-version" }

aa = { group = "de.ellpeck", name = "actuallyadditions", version.ref = "aa" }
create = { group = "maven.modrinth", name = "create", version.ref = "create" }
delight = { group = "maven.modrinth", name = "farmers-delight", version.ref = "delight" }
eio = { group = "com.enderio", name = "enderio-base", version.ref = "eio" }
eio-machines = { group = "com.enderio", name = "enderio-machines", version.ref = "eio" }
jade = { group = "maven.modrinth", name = "jade", version.ref = "jade" }
if = { group = "maven.modrinth", name = "industrial-foregoing", version.ref = "if" }
immersive = { group = "blusunrize.immersiveengineering", name = "ImmersiveEngineering", version.ref = "immersive" }
mek = { group = "mekanism", name = "Mekanism", version.ref = "mek" }
mi = { group = "aztech", name = "Modern-Industrialization", version.ref = "mi" }
jei-api = { group = "mezz.jei", name = "jei-1.21.1-neoforge-api", version.ref = "jei" }
jei = { group = "mezz.jei", name = "jei-1.21.1-neoforge", version.ref = "jei" }
patchouli-gen = { group = "xyz.brassgoggledcoders", name = "PatchouliProvider", version.ref = "patchouli-gen" }
rc = { group = "maven.modrinth", name = "railcraft-reborn", version.ref = "rc" }

[bundles]

mods-impl = [
    "aa",
    "create",
    "delight",
    "eio",
    "eio-machines",
    "if",
    "immersive",
    "jade",
    "mek",
    "mi",
    "patchouli-gen",
    "rc", 
]

mods-transitive = []

mods-compile = [
    "jei-api"
]

mods-runtime = [
    "jei"
]

[plugins]

neo-moddev = { id = "net.neoforged.moddev", version.ref = "neo-moddev" }

ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
