[versions]
minecraft = "1.21.1"
ragium = "0.4.0"

parchment-mc = "1.21.1"
parchment-map = "2024.11.17"

neo-moddev = "2.0.80"
neo-version = "21.1.156"

kff-version = "5.7.0"
kff-version-range = "[5.7,)"
ktlint = "12.2.0"

aa = "1.3.18+mc1.21.1"
ae2 = "19.2.8"
delight = "1.21.1-1.2.7"
dire = "6369120"
emi = "1.1.22+1.21.1"
guide = "21.1.8"
jade = "15.10.0+neoforge"
mek = "1.21.1-10.7.13.78"
patchouli-gen = "1.21.1-1.0.11-Snapshot.5"
rs2 = "2.0.0-beta.2"

[libraries]

kff = { group = "thedarkcolour", name = "kotlinforforge-neoforge", version.ref = "kff-version" }

aa = { group = "de.ellpeck", name = "actuallyadditions", version.ref = "aa" }
ae2 = { group = "org.appliedenergistics", name = "appliedenergistics2", version.ref = "ae2" }
delight = { group = "maven.modrinth", name = "farmers-delight", version.ref = "delight" }
dire = { group = "curse.maven", name = "just-dire-things-1002348", version.ref = "dire" }
emi = { group = "dev.emi", name = "emi-neoforge", version.ref  = "emi" }
guide = { group = "org.appliedenergistics", name = "guideme", version.ref = "guide" }
jade = { group = "maven.modrinth", name = "jade", version.ref = "jade" }
mek = { group = "mekanism", name = "Mekanism", version.ref = "mek" }
patchouli-gen = { group = "xyz.brassgoggledcoders", name = "PatchouliProvider", version.ref = "patchouli-gen" }
rs2 = { group = "com.refinedmods.refinedstorage", name = "refinedstorage-neoforge", version.ref = "rs2" }

[bundles]

mods-impl = [
    "aa",
    "ae2",
    "delight",
    "dire",
    "emi",
    "guide",
    "jade",
    "mek",
    "patchouli-gen",
    "rs2",
]

mods-transitive = []

mods-compile = []

mods-runtime = []

[plugins]

neo-moddev = { id = "net.neoforged.moddev", version.ref = "neo-moddev" }

ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
