[versions]
minecraft = "1.21.1"
ragium = "0.4.0"

parchment-mc = "1.21.1"
parchment-map = "2024.11.17"

neo-moddev = "2.0.78"
neo-version = "21.1.136"

kff-version = "5.7.0"
kff-version-range = "[5.7,)"
ktlint = "12.1.2"

aa = "1.3.17+mc1.21.1"
emi = "1.1.20+1.21.1"
guide = "21.1.6"
jade = "15.10.0+neoforge"
mek = "1.21.1-10.7.13.78"
patchouli-gen = "1.21.1-1.0.11-Snapshot.5"

[libraries]

kff = { group = "thedarkcolour", name = "kotlinforforge-neoforge", version.ref = "kff-version" }

aa = { group = "de.ellpeck", name = "actuallyadditions", version.ref = "aa" }
emi = { group = "dev.emi", name = "emi-neoforge", version.ref  = "emi" }
guide = { group = "org.appliedenergistics", name = "guideme", version.ref = "guide" }
jade = { group = "maven.modrinth", name = "jade", version.ref = "jade" }
mek = { group = "mekanism", name = "Mekanism", version.ref = "mek" }
patchouli-gen = { group = "xyz.brassgoggledcoders", name = "PatchouliProvider", version.ref = "patchouli-gen" }

[bundles]

mods-impl = [
    "aa",
    "emi",
    "guide",
    "jade",
    "mek",
    "patchouli-gen",
]

mods-transitive = []

mods-compile = []

mods-runtime = []

[plugins]

neo-moddev = { id = "net.neoforged.moddev", version.ref = "neo-moddev" }

ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
