[versions]
kotlin = "2.0.+"
minecraft = "1.21.1"
fabric-loom = "1.8-SNAPSHOT"
fabric-loader = "0.16.+"
fabric-api = "0.107.0+1.21.1"
fabric-yarn = "1.21.1+build.3"
fabric-kotlin = "1.12.+"

energy = "4.1.0"
jade = "15.8.2+fabric"
mod-menu = "11.0.3"
refined-storage = "2.0.0-milestone.4.9"
rei = "16.0.788"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
fabric-kotlin = { group = "net.fabricmc", name = "fabric-language-kotlin", version.ref = "fabric-kotlin" }

energy = { group = "teamreborn", name = "energy", version.ref = "energy" }
jade = { group = "maven.modrinth", name = "jade", version.ref = "jade" }
mod-modmenu = { group = "com.terraformersmc", name = "modmenu", version.ref = "mod-menu" }
rs-fabric = { group = "com.refinedmods.refinedstorage", name = "refinedstorage-fabric", version.ref = "refined-storage" }
rei = { group = "me.shedaniel", name = "RoughlyEnoughItems-fabric", version.ref = "rei" }

[bundles]
mods-fabric = [
    "fabric-api",
    "fabric-kotlin",
    "fabric-loader",
    "rs-fabric"
]
mods-include = [
    "energy"
]
mods-compile = []
mods-runtime = [
    "jade",
    "mod-modmenu",
    "rei"
]

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "12.1.1" }
