[versions]
minecraft = "1.21.1"
ragium = "0.1.2"

parchment-mc = "1.21.1"
parchment-map = "2024.11.17"

neo-moddev = "2.0.78"
neo-version = "21.1.117"

kff-version = "5.7.0"
kff-version-range = "[5.7,)"
ktlint = "12.1.2"

aa = "1.3.14+mc1.21.1"
ars = "5.4.2.938"
curious = "9.2.2+1.21.1"
cyclops = "6125969"
delight = "1.21.1-1.2.7"
evil = "6152878"
if = "1.21-3.6.22"
immersive = "1.21.1-12.0.0-182.88"
jade = "15.9.3+neoforge"
jei = "19.21.0.247"
mek = "1.21.1-10.7.8.70"
mi = "2.2.34"
patchouli-gen = "1.21.1-1.0.11-Snapshot.3"
powah = "6.1.5-neoforge"
rc = "1.2.5"
rei = "18.0.796"
theurgy = "1.58.2"

[libraries]

kff = { group = "thedarkcolour", name = "kotlinforforge-neoforge", version.ref = "kff-version" }

aa = { group = "de.ellpeck", name = "actuallyadditions", version.ref = "aa" }
ars = { group = "com.hollingsworth.ars_nouveau", name = "ars_nouveau-1.21.1", version.ref = "ars" }
curious = { group = "top.theillusivec4.curios", name = "curios-neoforge", version.ref = "curious" }
cyclops = { group = "curse.maven", name = "cyclops-core-232758", version.ref = "cyclops" }
delight = { group = "maven.modrinth", name = "farmers-delight", version.ref = "delight" }
evil = { group = "curse.maven", name = "evilcraft-74610", version.ref = "evil" }
jade = { group = "maven.modrinth", name = "jade", version.ref = "jade" }
if = { group = "maven.modrinth", name = "industrial-foregoing", version.ref = "if" }
immersive = { group = "blusunrize.immersiveengineering", name = "ImmersiveEngineering", version.ref = "immersive" }
mek = { group = "mekanism", name = "Mekanism", version.ref = "mek" }
mi = { group = "aztech", name = "Modern-Industrialization", version.ref = "mi" }
jei-api = { group = "mezz.jei", name = "jei-1.21.1-neoforge-api", version.ref = "jei" }
jei = { group = "mezz.jei", name = "jei-1.21.1-neoforge", version.ref = "jei" }
patchouli-gen = { group = "xyz.brassgoggledcoders", name = "PatchouliProvider", version.ref = "patchouli-gen" }
powah = { group = "maven.modrinth", name = "powah", version.ref = "powah" }
rc = { group = "maven.modrinth", name = "railcraft-reborn", version.ref = "rc" }
rei = { group = "me.shedaniel", name = "RoughlyEnoughItems-neoforge", version.ref = "rei" }
theurgy = { group = "com.klikli_dev", name = "theurgy-1.21.1-neoforge", version.ref = "theurgy" }

[bundles]

mods-impl = [
    "aa",
    "curious",
    "delight",
    "if",
    "immersive",
    "jade",
    "mek",
    "mi",
    "patchouli-gen",
    "rc",
]

mods-transitive = [
    "ars"
]

mods-compile = [
    "jei-api"
]

mods-runtime = [
    "jei"
]

[plugins]

neo-moddev = { id = "net.neoforged.moddev", version.ref = "neo-moddev" }

ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
