[versions]
minecraft = "1.21.1"
ragium = "0.5.0"

parchment-mc = "1.21.1"
parchment-map = "2024.11.17"

neo-moddev = "2.0.96"
neo-version = "21.1.186"

kff-version = "5.9.0"
kff-version-range = "[5.9,)"
ktlint = "12.3.0"

aa = "1.3.19+mc1.21.1"
ae2 = "19.2.12"
ars = "5.8.6.1139"
curious = "9.5.1+1.21.1"
delight = "1.21.1-1.2.8"
dire = "6369120"
emi = "1.1.22+1.21.1"
guide = "21.1.12"
jade = "15.10.1+neoforge"
mek = "1.21.1-10.7.14.79"
patchouli-gen = "1.21.1-1.0.11-Snapshot.5"
pneuma = "8.2.12+mc1.21.1"
replica = "1.21-1.1.27"
rs2 = "2.0.0-beta.2"

[libraries]

kff = { group = "thedarkcolour", name = "kotlinforforge-neoforge", version.ref = "kff-version" }

aa = { group = "de.ellpeck", name = "actuallyadditions", version.ref = "aa" }
ae2 = { group = "org.appliedenergistics", name = "appliedenergistics2", version.ref = "ae2" }
ars = { group = "com.hollingsworth.ars_nouveau", name = "ars_nouveau-1.21.1", version.ref = "ars" }
curious = { group = "top.theillusivec4.curios", name = "curios-neoforge", version.ref = "curious" }
delight = { group = "maven.modrinth", name = "farmers-delight", version.ref = "delight" }
dire = { group = "curse.maven", name = "just-dire-things-1002348", version.ref = "dire" }
emi = { group = "dev.emi", name = "emi-neoforge", version.ref  = "emi" }
guide = { group = "org.appliedenergistics", name = "guideme", version.ref = "guide" }
jade = { group = "maven.modrinth", name = "jade", version.ref = "jade" }
mek = { group = "mekanism", name = "Mekanism", version.ref = "mek" }
patchouli-gen = { group = "xyz.brassgoggledcoders", name = "PatchouliProvider", version.ref = "patchouli-gen" }
pneuma = { group = "me.desht.pneumaticcraft", name = "pneumaticcraft-repressurized", version.ref = "pneuma" }
replica = { group = "maven.modrinth", name = "replication", version.ref = "replica" }
rs2 = { group = "com.refinedmods.refinedstorage", name = "refinedstorage-neoforge", version.ref = "rs2" }

[bundles]

mods-impl = [
    "aa",
    "ae2",
    "curious",
    "delight",
    "emi",
    "guide",
    "jade",
    "mek",
    "patchouli-gen",
    "pneuma",
    "replica",
]

mods-transitive = [
    "ars"
]

mods-compile = []

mods-runtime = [
    "dire",
    "rs2",
]

[plugins]

neo-moddev = { id = "net.neoforged.moddev", version.ref = "neo-moddev" }

ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
